---
title: "Reading data into R with `readxl`"
author: "Abdul Rahman Shahab"
date: "9/29/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Attach the tidyverse, readxl, writexl and here packages:
library(tidyverse)
library(readxl)
library(writexl)
library(here)
library(pander)
```


Using `read_csv` to load data from a csv file

```{r, message=FALSE}
fish_counts <- read_csv(here("data", "fish_counts_curated.csv"))
fish_counts
```



Using readxl to upload data from an xlsx file
```{r}
library(readxl)
substrate_cover <- read_excel(
  here("data", "substrate_cover_curated.xlsx"),
  na = "-9999",
  skip = 4
)
substrate_cover
```

```{r}
library(readxl)
carp_cover_2000 <- read_excel(
  here("data", "substrate_cover_curated.xlsx"),
  range = "D12:I15")
carp_cover_2000
```


```{r}
library(readxl)
carp_cover_2000 <- read_excel(
  here("data", "substrate_cover_curated.xlsx"),
  range = "D12:I15", col_names = c("site_name", "transect", "quad", "plot_side", "type", "coverage"))
carp_cover_2000
```




```{r}
kelp_counts <- read_excel(
  here("data", "kelp_counts_curated.xlsx"),
  sheet = "abur"
)
kelp_counts
```


```{r}
excel_sheets(
  here("data", "kelp_counts_curated.xlsx")
)
```


```{r}
kelp_path <- here("data", "kelp_counts_curated.xlsx")

kelp_all_sites <- kelp_path %>% 
  excel_sheets() %>% 
  set_names() %>% 
  purrr::map_df(read_excel, kelp_path)
kelp_all_sites
```
